version: '3.4'

services:
  sftp:
    image: atmoz/sftp
    ports:
      - "2222:22"
    volumes:
      - ./.ssh/id_rsa:/etc/ssh/id_rsa
      - ./sftp-in:/home/foo/upload
    command: foo:pass:1001
    user: "${UID}:${GID}"

  zookeeper:
    hostname: myzookeeper
    container_name: zookeeper_container
    image: 'bitnami/zookeeper:3.7.0'
    environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
    restart: always

  nifi:
    image: apache/nifi:1.20.0
    container_name: airflow_nifi
    ports:
        - 8082:8080
        - 8443:8443
        - 8001:8000
    volumes:
        - ./nifi-out:/opt/nifi/nifi-current/fileprocessor
        - ./.ssh:/opt/nifi/nifi-current/ssh
        - ./images/nifi/logs:/opt/nifi/nifi-current/logs
        - ./images/nifi/jdbc:/opt/nifi/nifi-current/jdbc
    environment:
        - NIFI_WEB_HTTP_PORT=8080
        - NIFI_CLUSTER_IS_NODE=true
        - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
        - NIFI_ZK_CONNECT_STRING=myzookeeper:2181
        - NIFI_ELECTION_MAX_WAIT=30 sec
        - NIFI_SENSITIVE_PROPS_KEY='12345678901234567890A'
    restart: on-failure
    healthcheck:
        test: ["CMD", "curl", "-f", "http://nifi:8080/nifi/"]
        interval: 30s
        timeout: 20s
        retries: 3
